from typing import Protocol
from uuid import UUID

from domain.parking.parking_session import ParkingSession
from domain.parking.parking_spot import ParkingSpot


class ParkingSpotRepository(Protocol):
    def get(self, spot_id: UUID) -> ParkingSpot | None: ...
    def save(self, spot: ParkingSpot) -> None: ...


class ParkingSessionRepository(Protocol):
    def get(self, session_id: UUID) -> ParkingSession | None: ...
    def save(self, session: ParkingSession) -> None: ...
    def find_active_by_spot(self, spot_id: UUID) -> ParkingSession | None: ...